'use strict'

const assert=require('assert')
const Dag=require('../dag')

describe("Dag",()=>{
	it("selects node from node",()=>{
		const dagData={
			A:{},
		}
		const dag=new Dag(dagData,{
			A:true,
		})
		assert.deepEqual(dag.allParents,dagData)
		assert.deepEqual(dag.allChildren,{
			A:{},
		})
		assert.deepEqual(dag.visibleParents,{
			A:{},
		})
		assert.deepEqual(dag.visibleChildren,{
			A:{},
		})
		assert.deepEqual(dag.integratedAncestors,{
			A:{
				A:{},
			},
		})
		assert.deepEqual(dag.visibleDepthNodes,[
			{A:true},
		])
	})
	it("selects 2 nodes from 2 nodes",()=>{
		const dagData={
			A:{},
			B:{},
		}
		const dag=new Dag(dagData,{
			A:true,
			B:true,
		})
		assert.deepEqual(dag.allParents,dagData)
		assert.deepEqual(dag.allChildren,{
			A:{},
			B:{},
		})
		assert.deepEqual(dag.visibleParents,{
			A:{},
			B:{},
		})
		assert.deepEqual(dag.visibleChildren,{
			A:{},
			B:{},
		})
		assert.deepEqual(dag.integratedAncestors,{
			A:{
				A:{},
			},
			B:{
				B:{},
			},
		})
		assert.deepEqual(dag.visibleDepthNodes,[
			{A:true,B:true},
		])
	})
	it("selects chain from chain",()=>{
		const dagData={
			A:{},
			B:{A:true},
		}
		const dag=new Dag(dagData,{
			A:true,
			B:true,
		})
		assert.deepEqual(dag.allParents,dagData)
		assert.deepEqual(dag.allChildren,{
			A:{B:true},
			B:{},
		})
		assert.deepEqual(dag.visibleParents,{
			A:{},
			B:{A:true},
		})
		assert.deepEqual(dag.visibleChildren,{
			A:{B:true},
			B:{},
		})
		assert.deepEqual(dag.integratedAncestors,{
			A:{
				A:{},
			},
			B:{
				B:{},
			},
		})
		assert.deepEqual(dag.visibleDepthNodes,[
			{A:true},
			{B:true},
		])
	})
	it("selects node from chain",()=>{
		const dagData={
			A:{},
			B:{A:true},
		}
		const dag=new Dag(dagData,{
			B:true,
		})
		assert.deepEqual(dag.allParents,dagData)
		assert.deepEqual(dag.allChildren,{
			A:{B:true},
			B:{},
		})
		assert.deepEqual(dag.visibleParents,{
			B:{},
		})
		assert.deepEqual(dag.visibleChildren,{
			B:{},
		})
		assert.deepEqual(dag.integratedAncestors,{
			B:{
				A:{},
				B:{A:true},
			},
		})
		assert.deepEqual(dag.visibleDepthNodes,[
			{B:true},
		])
	})
	it("selects fork from fork",()=>{
		const dagData={
			A:{},
			B:{A:true},
			C:{A:true},
		}
		const dag=new Dag(dagData,{
			A:true,
			B:true,
			C:true,
		})
		assert.deepEqual(dag.allParents,dagData)
		assert.deepEqual(dag.allChildren,{
			A:{B:true,C:true},
			B:{},
			C:{},
		})
		assert.deepEqual(dag.visibleParents,{
			A:{},
			B:{A:true},
			C:{A:true},
		})
		assert.deepEqual(dag.visibleChildren,{
			A:{B:true,C:true},
			B:{},
			C:{},
		})
		assert.deepEqual(dag.integratedAncestors,{
			A:{
				A:{},
			},
			B:{
				B:{},
			},
			C:{
				C:{},
			},
		})
		assert.deepEqual(dag.visibleDepthNodes,[
			{A:true},
			{B:true,C:true},
		])
	})
	it("selects chain from fork",()=>{
		const dagData={
			A:{},
			B:{A:true},
			C:{A:true},
		}
		const dag=new Dag(dagData,{
			A:true,
			C:true,
		})
		assert.deepEqual(dag.allParents,dagData)
		assert.deepEqual(dag.allChildren,{
			A:{B:true,C:true},
			B:{},
			C:{},
		})
		assert.deepEqual(dag.visibleParents,{
			A:{},
			C:{A:true},
		})
		assert.deepEqual(dag.visibleChildren,{
			A:{C:true},
			C:{},
		})
		assert.deepEqual(dag.integratedAncestors,{
			A:{
				A:{},
			},
			C:{
				C:{},
			},
		})
		assert.deepEqual(dag.visibleDepthNodes,[
			{A:true},
			{C:true},
		])
	})
	it("selects 2 nodes from fork",()=>{
		const dagData={
			A:{},
			B:{A:true},
			C:{A:true},
		}
		const dag=new Dag(dagData,{
			B:true,
			C:true,
		})
		assert.deepEqual(dag.allParents,dagData)
		assert.deepEqual(dag.allChildren,{
			A:{B:true,C:true},
			B:{},
			C:{},
		})
		assert.deepEqual(dag.visibleParents,{
			B:{},
			C:{},
		})
		assert.deepEqual(dag.visibleChildren,{
			B:{},
			C:{},
		})
		assert.deepEqual(dag.integratedAncestors,{
			B:{
				A:{},
				B:{A:true},
			},
			C:{
				A:{},
				C:{A:true},
			},
		})
		assert.deepEqual(dag.visibleDepthNodes,[
			{B:true,C:true},
		])
	})
	it("selects diamond from diamond",()=>{
		const dagData={
			A:{},
			B:{A:true},
			C:{A:true},
			D:{B:true,C:true},
		}
		const dag=new Dag(dagData,{
			A:true,
			B:true,
			C:true,
			D:true,
		})
		assert.deepEqual(dag.allParents,dagData)
		assert.deepEqual(dag.allChildren,{
			A:{B:true,C:true},
			B:{D:true},
			C:{D:true},
			D:{},
		})
		assert.deepEqual(dag.visibleParents,{
			A:{},
			B:{A:true},
			C:{A:true},
			D:{B:true,C:true},
		})
		assert.deepEqual(dag.visibleChildren,{
			A:{B:true,C:true},
			B:{D:true},
			C:{D:true},
			D:{},
		})
		assert.deepEqual(dag.integratedAncestors,{
			A:{
				A:{},
			},
			B:{
				B:{},
			},
			C:{
				C:{},
			},
			D:{
				D:{},
			},
		})
		assert.deepEqual(dag.visibleDepthNodes,[
			{A:true},
			{B:true,C:true},
			{D:true},
		])
	})
	it("selects 3-chain from diamond",()=>{
		const dagData={
			A:{},
			B:{A:true},
			C:{A:true},
			D:{B:true,C:true},
		}
		const dag=new Dag(dagData,{
			A:true,
			B:true,
			D:true,
		})
		assert.deepEqual(dag.allParents,dagData)
		assert.deepEqual(dag.allChildren,{
			A:{B:true,C:true},
			B:{D:true},
			C:{D:true},
			D:{},
		})
		assert.deepEqual(dag.visibleParents,{
			A:{},
			B:{A:true},
			D:{B:true},
		})
		assert.deepEqual(dag.visibleChildren,{
			A:{B:true},
			B:{D:true},
			D:{},
		})
		assert.deepEqual(dag.integratedAncestors,{
			A:{
				A:{},
			},
			B:{
				B:{},
			},
			D:{
				C:{},
				D:{C:true},
			},
		})
		assert.deepEqual(dag.visibleDepthNodes,[
			{A:true},
			{B:true},
			{D:true},
		])
	})
	it("selects chain and node from a-shape",()=>{
		const dagData={
			A:{},
			B:{A:true},
			C:{A:true},
			D:{B:true,C:true},
			E:{C:true},
		}
		const dag=new Dag(dagData,{
			B:true,
			D:true,
			E:true,
		})
		assert.deepEqual(dag.allParents,dagData)
		assert.deepEqual(dag.allChildren,{
			A:{B:true,C:true},
			B:{D:true},
			C:{D:true,E:true},
			D:{},
			E:{},
		})
		assert.deepEqual(dag.visibleParents,{
			B:{},
			D:{B:true},
			E:{},
		})
		assert.deepEqual(dag.visibleChildren,{
			B:{D:true},
			D:{},
			E:{},
		})
		assert.deepEqual(dag.integratedAncestors,{
			B:{
				A:{},
				B:{A:true},
			},
			D:{
				C:{},
				D:{C:true},
			},
			E:{
				A:{},
				C:{A:true},
				E:{C:true},
			},
		})
		assert.deepEqual(dag.visibleDepthNodes,[
			{B:true,E:true},
			{D:true},
		])
	})
})
